import { getTeacherRequestArray } from "@/actions/adminAcions";
import Celebration from "@/components/Celebration/celebration";
import Loader from "@/components/Loader/page";
import Navbar from "@/components/Navbar/navbar";
import { Toaster } from "@/components/ui/toaster";
import { NextAuthProvider } from "@/components/wrapper/next-auth-provider";
import { ThemeProvider } from "@/components/wrapper/theme-provider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./(bare)/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const arrray = await getTeacherRequestArray();

  return (
    <html
      lang="en"
      data-theme="dark"
      className="dark"
      style={{ colorScheme: "dark" }}
    >
      <link rel="shortcut icon" href="biglogo.png" type="image/x-icon" />
      <body className={cn(inter.className, "flex flex-col h-[100dvh] ")}>
        <NextAuthProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Loader />
            <Navbar teacherArray={arrray.users} />
            <div className="mt-[120px]">
              <Celebration />
              {children}
            </div>
            <Toaster />
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
